apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: greet
  name: greet
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: greet
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: greet
    spec:
      containers:
      - image: jayaprakashkaluva/greeting-service:latest
        imagePullPolicy: Always
        name: greeting-service
        resources: {}
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30